# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TakePicture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'

  # Pods for TakePicture

  target 'TakePictureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TakePictureUITests' do
    # Pods for testing
  end

end
